# Generated by Django 4.0.3 on 2022-03-30 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=200, verbose_name='ImageNameNoext')),
                ('image_path', models.FilePathField(verbose_name='ImagePath')),
                ('image_object_path', models.FilePathField(verbose_name='GeojsonPath')),
                ('image_valid_times', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(verbose_name='user_id')),
                ('user_name', models.CharField(max_length=200, verbose_name='user_name')),
                ('user_email', models.EmailField(max_length=254, verbose_name='user_email')),
            ],
        ),
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_output', models.FilePathField(verbose_name='Save_GeojsonPath')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageObjects.user')),
                ('user_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageObjects.image')),
            ],
        ),
    ]
