# Generated by Django 4.0.3 on 2022-03-30 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageObjects', '0002_alter_image_image_name_alter_userinput_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='concurrent_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='image_bound_path',
            field=models.FilePathField(default=None, verbose_name='ImageBound'),
        ),
    ]
