# Generated by Django 4.0.3 on 2022-03-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageObjects', '0003_image_concurrent_count_image_image_bound_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinput',
            old_name='user_image',
            new_name='image_name',
        ),
        migrations.RenameField(
            model_name='userinput',
            old_name='user_id',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='userinput',
            name='user_output',
        ),
        migrations.AddField(
            model_name='userinput',
            name='user_image_output',
            field=models.FilePathField(default=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_bound_path',
            field=models.FilePathField(default=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_object_path',
            field=models.FilePathField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.FilePathField(),
        ),
    ]
